version: '3'
services:
  mongodb:
    image: mongo:3.0.2
    container_name: hapi_mongo
    restart: always
    volumes:
      - '../mongo_data:/data/db'
    ports:
      - 27017:27017

  backend:
    build: ./backend
    container_name: hapi_backend
    command: npm run dev
    # tty: true
    restart: always
    volumes:
      - './backend:/backend'
      - '/backend/node_modules'
    ports:
      - '9000:9000'
    depends_on:
      - mongodb
    env_file:
      - 'dev.env'